# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-node-browsers
    steps:
    - checkout
    - run: sudo apt update
    - run: sudo docker-php-ext-install zip
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-
    - store_test_results:
        path: tests    
workflows:
  version: 2
  workflow:
    jobs:
    - build
